### ISSUE TITLE
lookup里的http链接使用后未断开

### ISSUE THREAD

**Issue by leonliu315** [youzan/nsqJavaSDK#5]
LookupServiceImpl类的readFromUrl方法里，HttpURLConnection对象使用后并未调用disconnect方法，会造成链接泄露，请确认是否为bug。

**Comment by DoraALin** [comment]
greetings,
ObjectMapper.readTree() 在最后会调用JsonParser的close()方法。SDK依赖jackson来关闭连接。

**Comment by leonliu315** [comment]
想问下你们使用的是jdk7么？我这里用的是jdk8，但是实际用的时候的确是会出现链接持续增长的状况，如果加上disconnect则正常。

**Comment by leonliu315** [comment]
结果发现是因为使用原版lookupd的时候会出现，因为原版的lookupd没有listlookup这个url.....
